#!/bin/sh
set -e

_ARCH="amd64"
_MIRROR="http://debian.xtdv.net/debian"

lb config noauto \
	--verbose \
	--architecture "${_ARCH}" \
	--archive-areas "main contrib non-free" \
	--linux-packages "linux-image linux-headers" \
	--mirror-binary "${_MIRROR}" \
	--mirror-chroot "${_MIRROR}" \
	--mirror-bootstrap "${_MIRROR}" \
    "${@}"
