#!/bin/sh
set -e

_ARCH="amd64"
_MIRROR="http://deb.debian.org/debian"
_DIST="stable"

lb config noauto \
	--verbose \
	--architecture "${_ARCH}" \
	--distribution "${_DIST}" \
    --apt-source-archives "false" \
	--archive-areas "main contrib non-free" \
	--linux-packages "linux-image linux-headers" \
	--mirror-binary "${_MIRROR}" \
	--mirror-chroot "${_MIRROR}" \
	--mirror-bootstrap "${_MIRROR}" \
    "${@}"
