#!/bin/sh

## @TxGVNN

#set -x

Cmdline ()
{
    # Reading kernel command line
    for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
    do
        case "${_PARAMETER}" in
            live-config.username=*|username=*)
                LIVE_USERNAME="${_PARAMETER#*username=}"
                ;;
        esac
    done
}

Init (){
    if [ ! -d /lib/live/dots ] ; then
        exit 0;
    fi

    echo -n " dots"
}

Config (){
    chown ${LIVE_USERNAME}: /lib/live/dots -R
    cp -a /lib/live/dots/. "/home/${LIVE_USERNAME}/"
}

Cmdline
Init
Config
